# Generated by Django 3.2.13 on 2022-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnwithus', '0004_alter_courses_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='thumb',
            field=models.FileField(default=1, upload_to='video/%y'),
            preserve_default=False,
        ),
    ]
