# Generated by Django 3.2.13 on 2022-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnwithus', '0005_courses_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='thumb',
            field=models.FileField(blank=True, upload_to='thumb/%y'),
        ),
    ]
