# Generated by Django 3.2.13 on 2022-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnwithus', '0006_alter_courses_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentt',
            fields=[
                ('comm_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('profileid', models.PositiveIntegerField()),
                ('courseid', models.PositiveIntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
