# Generated by Django 3.2.13 on 2022-05-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnwithus', '0007_commentt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentt',
        ),
    ]
