# Generated by Django 3.2.13 on 2022-05-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnwithus', '0010_joinedcourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinedCourses',
        ),
    ]
